Discusssion Section (October 3)

In [3]:
import pandas as pd

**What is this data about?**
This data includes arthropod species occurence in California drylands taken and cleaned up from Global Biodiversity Information Facility.

**Is this data collected in-situ by the authors or is it a synthesis of multiple datasets?**
This repository includes data from multiple datasets.

**During what time frame were the observations in the dataset collected?**
Observations in this dataset were taken between 1945 and 2022.

**Does this dataset come with an associated metadata file?**
Yes, it does come with an associated metadata file.

**Does the dataset contain sensitive data?**
The data sensitive category for this dataset is considered non-sensitive data.

In [4]:
# Access metadata from repository
pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A3baf7289-bf90-4db3-ad11-58785c09b26e')

,attribute,description
0,class,taxonomic class of observed organism
1,order,taxonomic order of observed organism
2,family,taxonomic family of observed organism
3,genus,genus name
4,species,full latin binomial name
5,lat,latitude of occurrence record in decimal degrees
6,long,longitude of occurrence record in decimal degrees
7,eventDate,date and time of observation in YYYY-MM-DD HH:...
8,day,day of the month of observation
9,month,month of observation
10,year,observation year
11,institutionCode,institution code provided by GBIF (www.gbif.org)
12,coordinateUncertaintyInMeters,coordinate uncertainty in meters; NA indicate ...
13,basisOfRecord,"type of record provided by GBIF; one of ""HUMAN..."
14,individualCount,number of individuals (if provided) observed f...
15,datasetKey,unique dataset key provided by GBIF
16,bio1,"annual mean temperature (degrees Celsius, x10)"
17,bio10,mean temperature of warmest quarter (degrees C...
18,bio11,mean temperature of coldest quarter (degrees C...
19,bio12,annual precipitation (millimeters (mm))
20,bio13,precipitation of wettest month (mm)
21,bio14,precipitation of driest month (mm)
22,bio15,precipitation seasonality (percent)
23,bio16,precipitation of wettest quarter (mm)
24,bio17,precipitation of driest quarter (mm)
25,bio18,precipitation of warmest quarter (mm)
26,bio19,precipitation of coldest quarter (mm)
27,bio2,"annual mean diurnal range (degrees Celsius, x10)"
28,bio3,isothermality (percent)
29,bio4,"temperature seasonality (degrees Celsius, x100)"
30,bio5,max temperature of warmest month (degrees Cels...
31,bio6,min temperature of coldest month (degrees Cels...
32,bio7,"annual temperature range (degrees Celsius, x10)"
33,bio8,mean temperature of wettest month (degrees Cel...
34,bio9,mean temperature of driest quarter (degrees Ce...
35,dist,distance to the nearest major road (kilometers...
36,dem90_hf,elevation (meters); data from the National Ele...
37,lc_class,landcover classification from the University o...
38,ndvi,the mean normalized difference vegetation inde...
39,notes,all bioX variables are from the WorldClim data...

In [11]:
# Load data
prey = pd.read_csv('https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3A23d42528-1048-45d4-85d1-7e13b666e744')

# Check head of csv file
type(prey)

pandas.core.frame.DataFrame

`prey` is a pandas data frame.

In [12]:
# Show head of prey dataframe
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,...,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,...,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,...,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,...,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,...,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,...,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

We noticed there are 40 columns. Many of the columns are not descriptive (ex: bio1, bio2, etc.) The column names are also in camel case.

In [13]:
# Display maxcolumns
pd.set_option("display.max.columns", None)
prey.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104

The set_option() code above displays all of the columns of a dataframe instead of the first and last 10 columns.

In [ ]:
# The following code shows the first 5 rows of a dataframe
prey.head()

# The following code shows the last 5 rows of a dataframe.
prey.tail()

# The following code shows the metadata for the dataframe 
# (includes column names, number of entries, datatype of columns, memory usage, non-null values)
prey.info()

# The following code shows the amount of unique observations for each column 
prey.nunique()

In [27]:
# Change default setting in head
prey.head(10)

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institutionCode,coordinateUncertaintyInMeters,basisOfRecord,individualCount,datasetKey,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104
5,Insecta,Diptera,Syrphidae,Allograpta,Allograpta obliqua,37.842187,-122.272478,2020-05-02T10:28:25Z,2.0,5.0,2020,iNaturalist,917.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,6,144.511795,178.412857,105.581818,565.076050,122.171043,1.000000,87.983589,308.378662,7.063087,9.205670,308.378662,89.164856,51.079494,2885.461670,234.265152,60.451580,173.813568,105.581818,172.760529,0.365533,35.971046,urban,3031.351807
6,Insecta,Orthoptera,Acrididae,Schistocerca,Schistocerca nitens,33.854472,-117.817876,2022-07-24T19:59:00Z,24.0,7.0,2022,iNaturalist,160.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,7,177.032990,228.031799,132.172546,338.124573,72.213455,0.995521,89.869400,195.220841,6.873608,13.652244,183.396042,135.359924,55.000000,3758.806885,303.441711,60.240211,243.201508,136.165970,221.020721,0.705537,105.866028,urban,2929.991455
7,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,33.750705,-116.743667,2022-10-15T14:03:29Z,15.0,10.0,2022,iNaturalist,4.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,8,120.158730,199.906616,53.729237,616.566406,105.341469,3.252115,72.506027,306.442810,35.863651,60.013138,296.442810,157.927048,49.197884,5878.874512,302.063477,-16.578903,318.642364,58.158726,172.410843,1.145492,1639.430786,grassland,5714.669922
8,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,33.235500,-117.280700,2016-12-13T08:00:00Z,13.0,12.0,2016,iNaturalist,NaN,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,9,168.944000,217.027542,127.524216,302.635620,59.679543,1.225997,86.732315,166.990814,6.451993,12.225997,155.940826,115.709236,53.982101,3478.261719,275.912842,62.300415,213.612412,130.638260,209.373581,1.022442,95.028740,urban,3148.228271
9,Insecta,Lepidoptera,Nymphalidae,Vanessa,Vanessa cardui,37.323517,-122.174308,2019-04-29T15:22:16Z,29.0,4.0,2019,iNaturalist,5.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,10,131.805481,181.386352,89.509621,824.623535,164.044968,2.000000,86.375435,431.711121,11.555281,15.646415,431.711121,118.941368,54.445618,3672.007080,252.594223,35.436752,217.157471,89.509621,176.914505,1.444703,532.485596,evergreen_needleleaf,7056.129395

In [18]:
# The following code prints the dimensions of the dataframe
print(prey.shape)

# The following code prints a list the columns of the dataframe
print(prey.columns)

# The following code prints the data type of each column
print(prey.dtypes)

(111156, 40)
Index(['class', 'order', 'family', 'genus', 'species', 'lat', 'long',
       'eventDate', 'day', 'month', 'year', 'institutionCode',
       'coordinateUncertaintyInMeters', 'basisOfRecord', 'individualCount',
       'datasetKey', 'ID', 'bio1', 'bio10', 'bio11', 'bio12', 'bio13', 'bio14',
       'bio15', 'bio16', 'bio17', 'bio18', 'bio19', 'bio2', 'bio3', 'bio4',
       'bio5', 'bio6', 'bio7', 'bio8', 'bio9', 'dist', 'dem90_hf', 'lc_class',
       'ndvi'],
      dtype='object')
class                             object
order                             object
family                            object
genus                             object
species                           object
lat                              float64
long                             float64
eventDate                         object
day                              float64
month                            float64
year                               int64
institutionCode                   object
coordinateUncertaintyInMeters    float64
basisOfRecord                     object
individualCount                  float64
datasetKey                        object
ID                                 int64
bio1                             float64
bio10                            float64
bio11                            float64
bio12                            float64
bio13                            float64
bio14                            float64
bio15                            float64
bio16                            float64
bio17                            float64
bio18                            float64
bio19                            float64
bio2                             float64
bio3                             float64
bio4                             float64
bio5                             float64
bio6                             float64
bio7                             float64
bio8                             float64
bio9                             float64
dist                             float64
dem90_hf                         float64
lc_class                          object
ndvi                             float64
dtype: object

In [29]:
# Rename the institution code and the datasetkey column from camel to snake case
final_df = prey.rename(columns={'institutionCode' : 'institution_code',
                       'datasetKey' : 'dataset_key'})

# Display first 5 columns to check that renaming worked
final_df.head()

,class,order,family,genus,species,lat,long,eventDate,day,month,year,institution_code,coordinateUncertaintyInMeters,basisOfRecord,individualCount,dataset_key,ID,bio1,bio10,bio11,bio12,bio13,bio14,bio15,bio16,bio17,bio18,bio19,bio2,bio3,bio4,bio5,bio6,bio7,bio8,bio9,dist,dem90_hf,lc_class,ndvi
0,Insecta,Odonata,Libellulidae,Sympetrum,Sympetrum corruptum,37.173971,-121.856329,2020-09-29T08:24:00Z,29.0,9.0,2020,iNaturalist,684.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,1,141.925064,199.384964,89.602631,727.380493,151.920853,1.809903,89.132339,391.141083,7.979710,13.979711,391.141083,139.787125,53.000000,4352.049805,289.341888,27.307756,262.034149,89.602631,196.067307,8.935099,352.799927,grassland,6343.969238
1,Malacostraca,Isopoda,Armadillidiidae,Armadillidium,Armadillidium vulgare,37.688580,-122.436608,2021-12-04T14:49:59Z,4.0,12.0,2021,iNaturalist,6.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,2,136.366943,165.841537,104.141464,609.651916,126.271736,1.001933,87.368050,318.303192,8.236301,12.390024,318.301269,83.996452,53.266750,2455.836914,217.470047,61.847702,155.622360,107.227386,159.852875,2.005335,112.895271,grassland,4995.110352
2,Insecta,Hymenoptera,Apidae,Bombus,Bombus vosnesenskii,33.774911,-116.679713,2021-06-18T08:52:00Z,18.0,6.0,2021,iNaturalist,31.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,3,82.885788,161.338638,19.747343,724.200195,120.836441,4.910511,70.099121,353.376068,49.060783,77.778824,342.061676,144.624817,47.098640,5776.527344,254.696030,-47.440784,302.136810,20.866125,134.750717,4.422367,2315.607666,grassland,5118.055664
3,Insecta,Hymenoptera,Apidae,Apis,Apis mellifera,32.848001,-117.050126,2016-04-17T09:28:00Z,17.0,4.0,2016,iNaturalist,15.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,4,171.959030,221.238907,130.363754,323.523682,62.686253,1.000000,87.075172,179.273834,4.989321,9.743295,163.154465,118.763413,53.612831,3539.726807,286.711762,65.920944,220.790817,133.117722,213.238907,4.316342,199.882156,closed_shrubland,3649.374756
4,Insecta,Hemiptera,Lygaeidae,Oncopeltus,Oncopeltus fasciatus,32.739453,-117.133980,2019-04-06T18:44:31Z,6.0,4.0,2019,iNaturalist,16.0,HUMAN_OBSERVATION,NaN,50c9509d-22c7-4a22-a47d-8c48425ef4a7,5,171.996231,214.353073,136.138779,273.203491,58.141060,1.000000,91.661606,162.390411,4.000000,7.109778,142.560562,91.184349,50.718666,3033.009521,259.712738,81.205818,178.506927,138.277557,205.749908,0.651661,72.789574,urban,3468.256104